# Generated by Django 4.1.7 on 2024-02-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0005_archivos_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('template_description', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('template_json', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('doc_format', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Documentos.formatosdocumento')),
            ],
        ),
    ]
