# Generated by Django 4.1.7 on 2024-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatetemplates',
            name='template_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
