# Generated by Django 4.1.7 on 2024-02-18 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisExpedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documentos', '0005_archivos_persona'),
        ('SignatureVerification', '0002_alter_coordinatetemplates_template_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt_contract_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('wt_status', models.CharField(blank=True, max_length=150, null=True)),
                ('wt_doc_link', models.TextField(blank=True, null=True)),
                ('wt_returned_json', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MisExpedientes.expedientes')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Documentos.archivos')),
            ],
        ),
    ]
