# Generated by Django 4.1.7 on 2024-02-18 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0003_wtcontracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtcontracts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wtcontracts',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
