# Generated by Django 4.1.7 on 2024-02-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0020_personas_uuid_imss_personas_uuid_issste'),
        ('SignatureVerification', '0004_wtcontracts_date_created_wtcontracts_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtcontracts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.personas'),
        ),
    ]
