# Generated by Django 4.1.7 on 2024-02-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0005_alter_wtcontracts_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtSignatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrendador_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('arrendador_name', models.CharField(blank=True, max_length=150, null=True)),
                ('observador_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('observador_name', models.CharField(blank=True, max_length=150, null=True)),
                ('arrendatario_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('arrendatario_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email_title', models.CharField(blank=True, max_length=150, null=True)),
                ('email_message', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('wt_signatory_json', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wt_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SignatureVerification.wtcontracts')),
            ],
        ),
    ]
