# Generated by Django 4.1.7 on 2024-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0006_wtsignatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtsignatures',
            name='wt_contract',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
