# Generated by Django 4.1.7 on 2024-02-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SignatureVerification', '0007_alter_wtsignatures_wt_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtsignatures',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
