# Generated by Django 4.1.7 on 2024-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0008_wtsignatures_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtsignatures',
            name='wt_json_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
