# Generated by Django 4.1.7 on 2024-02-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignatureVerification', '0009_wtsignatures_wt_json_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtWebhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(blank=True, max_length=150, null=True)),
                ('hook_status', models.CharField(blank=True, max_length=150, null=True)),
                ('documentURL', models.TextField(blank=True, null=True)),
                ('certificateURL', models.TextField(blank=True, null=True)),
                ('pscCertificateURL', models.TextField(blank=True, null=True)),
                ('hook_json', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wt_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SignatureVerification.wtcontracts')),
            ],
        ),
    ]
