# Generated by Django 4.1.7 on 2023-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarNacimientoCURP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_created=True)),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('lugarnacimiento', models.CharField(max_length=100, unique=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NacionalidadCURP',
        ),
    ]
