# Generated by Django 4.1.7 on 2023-03-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0004_paises_alter_lugarnacimientocurp_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=200, unique=True)),
                ('municipio', models.CharField(max_length=200, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.CharField(max_length=250, unique=True)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios')),
            ],
        ),
    ]
