# Generated by Django 4.1.7 on 2023-03-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0005_municipios_colonia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacionesGPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(help_text='Clasificación de ocupaciones según CMO', unique=True)),
                ('grupoprincipal', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OcupacionesGPrincipalCMO',
                'verbose_name_plural': 'OcupacionesGPrincipalCMO',
            },
        ),
        migrations.AlterModelOptions(
            name='colonia',
            options={'verbose_name': 'Colonia', 'verbose_name_plural': 'Colonias'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='lugarnacimientocurp',
            options={'verbose_name': 'Lugar de Nacimiento (CURP)', 'verbose_name_plural': 'Lugares de Nacimiento (CURP)'},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'verbose_name': 'Municipios', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidades',
            options={'verbose_name': 'Nacionalidades', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'verbose_name': 'Paises', 'verbose_name_plural': 'Paises'},
        ),
    ]
