# Generated by Django 4.1.7 on 2023-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0006_ocupacionesgprincipal_alter_colonia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecorto', models.CharField(max_length=30, unique=True)),
                ('nombrecomercial', models.CharField(max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
