# Generated by Django 4.1.7 on 2023-03-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0007_bancos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancos',
            options={'verbose_name': 'Bancos', 'verbose_name_plural': 'Bancos'},
        ),
    ]
