# Generated by Django 4.1.7 on 2023-03-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0008_alter_bancos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosCiviles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estados Civiles',
                'verbose_name_plural': 'EstadosCiviles',
            },
        ),
    ]
