# Generated by Django 4.1.7 on 2023-06-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0009_estadosciviles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoINE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
