# Generated by Django 4.1.7 on 2023-12-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0010_tipoine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipInmobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
