# Generated by Django 4.1.7 on 2023-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0011_tipinmobiliario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipinmobiliario',
            name='fecha_publicacion',
            field=models.DateField(default='2023-12-26'),
            preserve_default=False,
        ),
    ]
