# Generated by Django 4.1.7 on 2024-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0012_tipinmobiliario_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('persona', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
