# Generated by Django 4.1.7 on 2024-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0013_folios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folios',
            options={'verbose_name_plural': 'Folios'},
        ),
        migrations.AlterField(
            model_name='folios',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
