# Generated by Django 4.1.7 on 2024-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0014_alter_folios_options_alter_folios_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folios',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
