# Generated by Django 4.1.7 on 2023-03-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Una clave que identifique al documento', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del coumento', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipos de Documento',
                'verbose_name_plural': 'TiposDocumentos',
            },
        ),
        migrations.CreateModel(
            name='FormatosDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('version', models.CharField(default='1', help_text='Versión del Documento: Ej:1.0.0 , 1.0, A1, etc.', max_length=100)),
                ('contenido', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Documentos.tiposdocumento')),
            ],
        ),
    ]
