# Generated by Django 4.1.7 on 2023-03-29 18:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatosdocumento',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
