# Generated by Django 4.1.7 on 2023-03-29 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_alter_formatosdocumento_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatosdocumento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatosdocumento',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
