# Generated by Django 4.1.7 on 2023-11-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0020_personas_uuid_imss_personas_uuid_issste'),
        ('Documentos', '0004_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.personas'),
            preserve_default=False,
        ),
    ]
