# Generated by Django 4.1.7 on 2024-01-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MisCobranzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobranzasPlantillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('mail', 'Mail'), ('llamar', 'Llamar')], max_length=10)),
                ('Frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('biannual', 'Semestral')], max_length=10)),
                ('name_subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
