# Generated by Django 4.1.7 on 2024-01-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCobranzas', '0002_cobranzasplantillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranzasmessages',
            name='email_subject',
            field=models.CharField(default='Recordatorio de pago', max_length=100),
        ),
    ]
