# Generated by Django 4.1.7 on 2024-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCobranzas', '0003_cobranzasmessages_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzasmessages',
            name='body',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='cobranzasplantillas',
            name='body',
            field=models.TextField(max_length=1500),
        ),
    ]
