# Generated by Django 4.1.7 on 2024-01-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCobranzas', '0004_alter_cobranzasmessages_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranzasmessages',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
