# Generated by Django 4.1.7 on 2023-10-31 01:02

import MisExpedientes.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaExpedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('expediente_nombre', models.FileField(upload_to=MisExpedientes.models.file_par, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'bmp'])])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('expediente_categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MisExpedientes.categoriaexpedientes')),
            ],
        ),
    ]
