# Generated by Django 4.1.7 on 2023-10-09 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponses',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponses',
            name='curp',
            field=models.TextField(default=''),
        ),
    ]
