# Generated by Django 4.1.7 on 2023-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0002_reponses_creado_en_reponses_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponses',
            name='peticion',
            field=models.TextField(choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE')], default='IMSS'),
            preserve_default=False,
        ),
    ]
