# Generated by Django 4.1.7 on 2023-10-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0003_reponses_peticion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponses',
            name='peticion',
        ),
    ]
