# Generated by Django 4.1.7 on 2023-10-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0004_remove_reponses_peticion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponses',
            old_name='curp',
            new_name='transaction_id',
        ),
    ]
