# Generated by Django 4.1.7 on 2023-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0005_rename_curp_reponses_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponses',
            name='curp',
            field=models.TextField(default=''),
        ),
    ]
