# Generated by Django 4.1.7 on 2023-03-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0005_personas_estadocivil'),
        ('Generales', '0009_estadosciviles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='Calle : ', max_length=150)),
                ('cruzamiento1', models.CharField(blank=True, default='Cruzamiento :', max_length=150, null=True)),
                ('cruzamiento2', models.CharField(blank=True, default='Cruzamiento 2:', max_length=150, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('colonia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.colonia')),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.personas')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.estados')),
                ('municipio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inmuebles.tipoinmueble')),
            ],
        ),
    ]
