# Generated by Django 4.1.7 on 2023-04-02 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Normativas', '0001_initial'),
        ('Inmuebles', '0002_inmueble_usodesuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='usodesuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Normativas.usodesuelo'),
        ),
    ]
