# Generated by Django 4.1.7 on 2023-04-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0006_alter_inmueble_usodesuelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='usodesuelo',
        ),
    ]
