# Generated by Django 4.1.7 on 2023-04-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0009_alter_inmueble_uso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='uso',
            new_name='usosuelo',
        ),
    ]
