# Generated by Django 4.1.7 on 2023-04-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0012_inmueble_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='uso',
        ),
    ]
