# Generated by Django 4.1.7 on 2023-04-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Normativas', '0003_alter_sustentolegal_nombre_alter_usodesuelo_uso'),
        ('Inmuebles', '0016_inmueble_usosuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='usosuelo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Normativas.usodesuelo'),
        ),
    ]
