# Generated by Django 4.1.7 on 2023-04-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0020_remove_inmueble_usosuelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='municipio',
        ),
    ]
