# Generated by Django 4.1.7 on 2023-04-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0021_remove_inmueble_estado_remove_inmueble_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='cruzamiento2',
            field=models.CharField(blank=True, default='Cruzamiento 2:', max_length=155, null=True),
        ),
    ]
