# Generated by Django 4.1.7 on 2023-04-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0022_alter_inmueble_cruzamiento2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo',
        ),
    ]
