# Generated by Django 4.1.7 on 2023-04-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0023_remove_inmueble_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Inmuebles.tipoinmueble'),
        ),
    ]
