# Generated by Django 4.1.7 on 2023-04-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0024_inmueble_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo',
        ),
    ]
