# Generated by Django 4.1.7 on 2023-04-03 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0025_remove_inmueble_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Inmuebles.tipoinmueble'),
            preserve_default=False,
        ),
    ]
