# Generated by Django 4.1.7 on 2023-04-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Normativas', '0004_alter_usodesuelo_uso'),
        ('Inmuebles', '0026_inmueble_tipo_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='uso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Normativas.usodesuelo'),
            preserve_default=False,
        ),
    ]
