# Generated by Django 4.1.7 on 2023-04-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0027_inmueble_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosInmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Inmuebles/fotos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inmueble_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inmuebles.inmueble')),
            ],
        ),
    ]
