# Generated by Django 4.1.7 on 2023-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0028_fotosinmuebles'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='num_interior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
