# Generated by Django 4.1.7 on 2023-03-26 08:41

import PersonasFisicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[PersonasFisicas.models.validar_rfc])),
                ('curp', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name': 'PersonaFisica',
                'verbose_name_plural': 'PersonasFisicas',
            },
        ),
    ]
