# Generated by Django 4.1.7 on 2023-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonasFisicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='apellido2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='nombre',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
