# Generated by Django 4.1.7 on 2023-03-26 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0003_nacionalidades'),
        ('PersonasFisicas', '0002_personafisica_apellido2_personafisica_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='creado_en',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='fnacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='lugarNacimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.lugarnacimientocurp'),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
