# Generated by Django 4.1.7 on 2023-03-28 05:35

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0006_ocupacionesgprincipal_alter_colonia_options_and_more'),
        ('PersonasFisicas', '0003_personafisica_creado_en_personafisica_fnacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='calle',
            field=models.CharField(default='Calle : ', max_length=150),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='colonia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.colonia'),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='correo_electronico',
            field=models.EmailField(default=None, help_text='Correo eléctronico', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='cruzamiento1',
            field=models.CharField(blank=True, default='Cruzamiento :', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='cruzamiento2',
            field=models.CharField(blank=True, default='Cruzamiento 2:', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.estados'),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='municipio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios'),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='telefono_principal',
            field=phone_field.models.PhoneField(default=None, help_text='Número de teléfono móvil o número principal', max_length=31),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='telefono_secundario',
            field=phone_field.models.PhoneField(blank=True, default=None, help_text='Número de teléfono móvil o número principal', max_length=31),
        ),
    ]
