# Generated by Django 4.1.7 on 2023-04-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Generales', '0009_estadosciviles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LF', 'LEY FEDERAL'), ('LE', 'LEY ESTATAL'), ('LM', 'LEY MUNICIPAL'), ('NOE', 'NORMATIVA ESTATAL'), ('NMU', 'NORMATIVA MUNICIPAL'), ('OT', 'OTROS'), ('SE', 'SIN ESPECIFICAR'), ('NA', 'NO APLICA')], default='NA', max_length=4, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la normativa o ley que aplica', max_length=300, unique=True)),
                ('articulo', models.CharField(blank=True, help_text='Articulo al que hace referencia', max_length=300, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios')),
            ],
        ),
        migrations.CreateModel(
            name='Usodesuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(help_text='Uso de suelo', max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('sustento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Normativas.sustentolegal')),
            ],
        ),
    ]
