# Generated by Django 4.1.7 on 2023-04-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normativas', '0002_alter_usodesuelo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustentolegal',
            name='nombre',
            field=models.CharField(help_text='Nombre de la normativa o ley que aplica', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='usodesuelo',
            name='uso',
            field=models.CharField(help_text='Uso de suelo', max_length=250),
        ),
    ]
