# Generated by Django 4.1.7 on 2023-04-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normativas', '0003_alter_sustentolegal_nombre_alter_usodesuelo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usodesuelo',
            name='uso',
            field=models.CharField(help_text='Uso de suelo', max_length=200),
        ),
    ]
