# Generated by Django 4.1.7 on 2023-04-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0009_estadosciviles'),
        ('Normativas', '0004_alter_usodesuelo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustentolegal',
            name='articulo',
            field=models.CharField(blank=True, help_text='Articulo al que hace referencia', max_length=300, null=True, verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='sustentolegal',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='sustentolegal',
            name='nombre',
            field=models.CharField(help_text='Nombre de la normativa o ley que aplica', max_length=250, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sustentolegal',
            name='tipo',
            field=models.CharField(choices=[('LF', 'LEY FEDERAL'), ('LE', 'LEY ESTATAL'), ('LM', 'LEY MUNICIPAL'), ('NOE', 'NORMATIVA ESTATAL'), ('NMU', 'NORMATIVA MUNICIPAL'), ('OT', 'OTROS'), ('SE', 'SIN ESPECIFICAR'), ('NA', 'NO APLICA')], default='NA', max_length=4, unique=True, verbose_name='Tipo'),
        ),
    ]
