# Generated by Django 4.1.7 on 2023-04-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0005_personas_estadocivil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(max_length=10, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, max_length=350, null=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('investigado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.personas')),
            ],
        ),
    ]
