# Generated by Django 4.1.7 on 2023-04-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigacion',
            old_name='aprovado',
            new_name='aprobado',
        ),
    ]
