# Generated by Django 4.1.7 on 2023-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0003_alter_investigacion_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='burojson',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='satblacklistjson',
            field=models.TextField(default=''),
        ),
    ]
