# Generated by Django 4.1.7 on 2023-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0004_investigacion_burojson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='antecedentesjson',
            field=models.TextField(default=''),
        ),
    ]
