# Generated by Django 4.1.7 on 2023-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0005_investigacion_antecedentesjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='estudiosprofesionalesjson',
            field=models.TextField(default=''),
        ),
    ]
