# Generated by Django 4.1.7 on 2023-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0006_investigacion_estudiosprofesionalesjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='listanegraintl',
            field=models.TextField(default=''),
        ),
    ]
