# Generated by Django 4.1.7 on 2023-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0008_investigacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='nombre_archivo',
            field=models.TextField(default=None),
        ),
    ]
