# Generated by Django 4.1.7 on 2024-01-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0009_investigacion_nombre_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigacion',
            options={'get_latest_by': 'creado_en'},
        ),
        migrations.CreateModel(
            name='InvestigacionPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('aval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aval_investigacion', to='Investigaciones.investigacionpremium')),
                ('conyugue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conyugue_investigacion', to='Investigaciones.investigacionpremium')),
                ('madre_conyugue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='madre_conyugue_investigacion', to='Investigaciones.investigacionpremium')),
                ('madre_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='madre_investigacion', to='Investigaciones.investigacionpremium')),
                ('padre_conyugue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre_conyugue_investigacion', to='Investigaciones.investigacionpremium')),
                ('padre_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre_investigacion', to='Investigaciones.investigacionpremium')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigacion_principal', to='Investigaciones.investigacion')),
            ],
        ),
    ]
