# Generated by Django 4.1.7 on 2024-02-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0009_investigacion_nombre_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigacion',
            options={'get_latest_by': 'creado_en'},
        ),
    ]
