# Generated by Django 4.1.7 on 2024-02-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Investigaciones', '0010_alter_investigacion_options_investigacionpremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacionpremium',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
