# Generated by Django 4.1.7 on 2024-02-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0012_alter_investigacionpremium_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacionpremium',
            name='aval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aval_investigacion', to='Investigaciones.investigacion'),
        ),
        migrations.AlterField(
            model_name='investigacionpremium',
            name='conyugue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conyugue_investigacion', to='Investigaciones.investigacion'),
        ),
        migrations.AlterField(
            model_name='investigacionpremium',
            name='madre_conyugue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='madre_conyugue_investigacion', to='Investigaciones.investigacion'),
        ),
        migrations.AlterField(
            model_name='investigacionpremium',
            name='madre_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='madre_investigacion', to='Investigaciones.investigacion'),
        ),
        migrations.AlterField(
            model_name='investigacionpremium',
            name='padre_conyugue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre_conyugue_investigacion', to='Investigaciones.investigacion'),
        ),
        migrations.AlterField(
            model_name='investigacionpremium',
            name='padre_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre_investigacion', to='Investigaciones.investigacion'),
        ),
    ]
