# Generated by Django 4.1.7 on 2024-02-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0014_alter_investigacionpremium_aval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=350, null=True)),
                ('parentesco', models.TextField(blank=True, max_length=350, null=True)),
                ('telefono', models.TextField(blank=True, max_length=10, null=True)),
                ('notas', models.TextField(blank=True, max_length=350, null=True)),
                ('investigacion_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conyugue_investigacion', to='Investigaciones.investigacionpremium')),
            ],
        ),
    ]
