# Generated by Django 4.1.7 on 2024-02-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0015_referencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencias',
            name='investigacion_premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Investigaciones.investigacionpremium'),
        ),
    ]
