# Generated by Django 4.1.7 on 2024-03-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0016_alter_referencias_investigacion_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacionpremium',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='desempenio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='es_empleado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='notas_valemp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='puesto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='rfc',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='salario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investigacionpremium',
            name='trabaja_ahi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='validacionEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=350, null=True)),
                ('razonsocial', models.TextField(blank=True, max_length=350, null=True)),
                ('investigacion_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Investigaciones.investigacionpremium')),
            ],
        ),
    ]
