# Generated by Django 4.1.7 on 2025-04-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investigaciones', '0010_alter_investigacion_options'),
        ('Investigaciones', '0017_investigacionpremium_antiguedad_and_more'),
    ]

    operations = [
    ]
