# Generated by Django 4.1.7 on 2024-01-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CargarCredito', '0002_userpayment_date_created_userpayment_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
