# Generated by Django 4.1.7 on 2024-01-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CargarCredito', '0003_alter_userpaymenthistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
