# Generated by Django 4.1.7 on 2024-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CargarCredito', '0004_userpaymenthistory_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
