# Generated by Django 4.1.7 on 2024-01-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingSystem', '0003_ticketcomment_creator_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=25),
        ),
    ]
