# Generated by Django 4.1.7 on 2023-03-29 22:30

import Personas.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Generales', '0008_alter_bancos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[Personas.models.validar_rfc])),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('razonsocial', models.CharField(help_text='Nombre completo o Razón social', max_length=300)),
                ('nombre', models.CharField(default=' ', max_length=150)),
                ('apellido2', models.CharField(blank=True, max_length=150)),
                ('fnacimiento', models.DateField(default=datetime.datetime.now)),
                ('telefono_principal', phone_field.models.PhoneField(default=None, help_text='Número de teléfono móvil o número principal', max_length=31)),
                ('telefono_secundario', phone_field.models.PhoneField(blank=True, default=None, help_text='Número de teléfono móvil o número principal', max_length=31)),
                ('correo_electronico', models.EmailField(default=None, help_text='Correo eléctronico', max_length=254, unique=True)),
                ('calle', models.CharField(default='Calle : ', max_length=150)),
                ('cruzamiento1', models.CharField(blank=True, default='Cruzamiento :', max_length=150, null=True)),
                ('cruzamiento2', models.CharField(blank=True, default='Cruzamiento 2:', max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('colonia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.colonia')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.estados')),
                ('lugarNacimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.lugarnacimientocurp')),
                ('municipio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.municipios')),
            ],
        ),
    ]
