# Generated by Django 4.1.7 on 2023-03-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name': 'Personas', 'verbose_name_plural': 'Personas'},
        ),
    ]
