# Generated by Django 4.1.7 on 2023-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_alter_personas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='apellido1',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
    ]
