# Generated by Django 4.1.7 on 2023-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_personas_apellido1'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='tipo',
            field=models.CharField(choices=[('PF', 'PERSONA FISICA'), ('PM', 'PERSONA MORAL')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
