# Generated by Django 4.1.7 on 2023-03-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0009_estadosciviles'),
        ('Personas', '0004_personas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='estadocivil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Generales.estadosciviles'),
            preserve_default=False,
        ),
    ]
