# Generated by Django 4.1.7 on 2023-04-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_personas_estadocivil'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='direccionine',
            field=models.TextField(default=''),
        ),
    ]
