# Generated by Django 4.1.7 on 2023-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_personas_direccionine'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='ine',
            field=models.TextField(default=''),
        ),
    ]
