# Generated by Django 4.1.7 on 2023-04-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_personas_ine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='ine',
            new_name='inejson',
        ),
    ]
