# Generated by Django 4.1.7 on 2023-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_rename_ine_personas_inejson'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='numExterior',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='numInterior',
            field=models.CharField(blank=True, default='..', max_length=150, null=True),
        ),
    ]
