# Generated by Django 4.1.7 on 2023-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0009_personas_numexterior_personas_numinterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='correo_electronico',
            field=models.EmailField(default='persona@legalbit.mx', help_text='Correo eléctronico', max_length=254),
        ),
    ]
