# Generated by Django 4.1.7 on 2023-05-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0010_alter_personas_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='inejson2',
            field=models.TextField(default=''),
        ),
    ]
