# Generated by Django 4.1.7 on 2023-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0011_personas_inejson2'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='uuidnss',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personas',
            name='uuidnss_sem',
            field=models.TextField(default=''),
        ),
    ]
