# Generated by Django 4.1.7 on 2023-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_personas_uuidnss_personas_uuidnss_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='inefront',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='personas',
            name='inerevers',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
