# Generated by Django 4.1.7 on 2023-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_personas_inefront_personas_inerevers'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='validaine',
            field=models.TextField(default=''),
        ),
    ]
