# Generated by Django 4.1.7 on 2023-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0014_personas_validaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
