# Generated by Django 4.1.7 on 2023-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0015_personas_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='cic_ine',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personas',
            name='clave_elector',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personas',
            name='identificador_ine',
            field=models.TextField(default=''),
        ),
    ]
