# Generated by Django 4.1.7 on 2023-06-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0016_personas_cic_ine_personas_clave_elector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='inefront',
            field=models.ImageField(blank=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='inerevers',
            field=models.ImageField(blank=True, upload_to='docs'),
        ),
    ]
