# Generated by Django 4.1.7 on 2023-08-29 01:18

import Personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0018_personas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='curp',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='personas',
            name='rfc',
            field=models.CharField(max_length=13, validators=[Personas.models.validar_rfc]),
        ),
    ]
