# Generated by Django 4.1.7 on 2023-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0019_alter_personas_curp_alter_personas_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='uuid_imss',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personas',
            name='uuid_issste',
            field=models.TextField(default=''),
        ),
    ]
